var langue = (
    {
        mg : {
            pharmacie :"Tranom-panafody",
            recherche : "Hitady...",
            bienvenue : "Tongasoa ...",
            pharmacie_desc : "Vidio ny fanafodinao",
            medecin : "Dokotera",
            medecin_desc : "Fandrio  ny fotoananao",
            localistation : "Toerana",
            localistation_desk : "Toerana misy anao",
            forum : "Fanehoan-kevitra",
            forum_desk : "Zaraio ato ny hevitrao",
            acceuil : "Fandraisana",
            liste_pharmacie : "Lisitra",
            position : "Adiresy",
            contacter : "Hiantso",
            parking : "Azo itondrana fiara",
            commentaire : "Kaomentera",  
            noter : "Naotena",
            signaler : "Tatitra",
            votre_commentaire : "Ny kaomontera anao:",
            tomady : "Inona i Tomady?",
            definition : "Tomady dia fanavaozana noforonin'ny tanora mpianatra tia ny teknolojia vaovao. ",
            langue : "Safidio ny fiteny",
            condition : "Fomba fampiasa",
            condition_test : "Ny tanjon'ity antontan-taratasy ity dia ny hamaritana ny fepetra sy ny fepetra izay amin'ny lafiny iray, izay antsoina avy eo hoe MPANOMPO, manome ny tranokala sy ny serivisy ho azon'ny mpampiasa azy, ary amin'ny lafiny iray, ny fomba izay idiran'ny mpampiasa ny tranokala sy mampiasa ny serivisy. Ny fifandraisana rehetra amin'ny tranokala dia iharan'ny fanarahana ireo fepetra ireo. Ho an'ny mpampiasa, ny fidirana tsotra amin'ny tranokalan'ny PUBLISHER amin'ity adiresy URL manaraka ity dia midika fanekena ny fepetra rehetra voalaza etsy ambany."
        },
        fr: {
            pharmacie : "Pharmacie",
            recherche : "Recherche...",
            bienvenue : "Bienvenue ...",
            pharmacie_desc : "Achetez votre médicament",
            medecin : "Médecin",
            medecin_desc : "Prenez votre rendez vous ",
            localistation : "Localisation",
            localistation_desk : "Voir votre position",
            forum : "Forum",
            forum_desk : "Donnez votre avis",
            acceuil : "Accueil",
            liste_pharmacie : "Liste",
            position : "Position",
            contacter : "Contacter",
            parking : "Parking sécurisé",
            commentaire : "Commentaires",
            noter : "Noter",
            signaler : "Signaler",
            votre_commentaire : "Votre commentaire:",
            tomady : "C'est quoi Tomady",
            definition : "Tomady est une innovation crée par des jeune étudiant passionnés de nouvelle Téchnologie. ",
            langue : "Choisir votre langue",
            condition : "Terms of use",
            pharmacie :"Pharmacy",
            bienvenue : "Welcome ...",   
            pharmacie_desc : "Buy your medicine",      
            medecin : "Doctor",
            medecin_desc : "Make your appointment",
            localistation : "Location",
            localistation_desk : "See your position",
            forum : "Forum",
            forum_desk : "Share your opinion",
            acceuil : "Home",
            liste_pharmacie : "list",
            position : "Position",
            contacter : "Contact",
            parking : "Secure parking",
            commentaire : "Comments",
            noter : "Score",
            signaler : "Report",
            votre_commentaire : "Your comment:",
            tomady : "What is Tomady",
            definition : " Tomady is an innovation created by young students passionate about new technology.",
            langue : "Choose your language",
            condition_test : "The purpose of this document is to define the terms and conditions under which on the one hand, hereinafter referred to as the PUBLISHER, makes the site and the services available on the site available to its users, and on the other hand, the way in which the user accesses the site and uses its services. Any connection to the site is subject to compliance with these conditions. For the user, the simple access to the PUBLISHER's site at the following URL address implies acceptance of all the conditions described below.",
            condition : "Terms of use",
        }
    }
)
export default langue